### PR TITLE
Added a folder for users to put utility scripts and created a python script for topology backups via API

### PR DESCRIPTION
**Pull request by mbarfiel**
script to perform API backups of topologies for accidental topo
deletions. Script should be self-expnaitory but setup in a cron job or
Jenkins to backup topologies.

## Proposed Changes

Adding a folder and utility script/tool. I didn't see a place for that in Velocity directory. Also, added a script that backs up Velocity topologies (TBML) so they can be restored without doing a full DB restore when someone messes up a topology.
## Types of Changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x ] New Project
- [ ] Enhancement
- [ ] Refactor
- [ ] Bug Fix

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask @kalina-k. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ x] Project name conforms to the naming convention described [here](https://github.com/Spirent/Velocity-assets/blob/master/README.md)
- [ x] Project name is unique within the repository
- [ x] Project exists in the appropriate directory based on its category and class, e.g. Drivers/Community
- [ ] Project contains a file called documentation/readme.txt with metadata necessary for the [catalog](https://developer.spirent.com/). The readme.txt file should contain _at least_ these 4 lines at the top of the file:
      Project: Name of project
      Description: 80 or so characters describing the contents of the project
      Category: ("driver" | "task" | "dashboard")
      Class: ("Community" | "Tested by Spirent" | "Reference")

### CODE REVIEW

**Comment by alexorr** [comment]
Please create the documentation/readme.txt file with the required info. It is needed to generate the HTML for developer.spirent.com. It will also automatically create the readme.MD file, so no need to make one yourself. You can copy all the good info you currently have in the readme.md file underneath the required info fields in the readme.txt file.

**Comment by mbarfiel** [comment]
Added readme.txt so script can get updated

**Comment by alexorr** [comment]
Merging this, but planning to move this project to the newly created 'Tools' folder.

**Comment by alexorr** [comment]
Still need to move this to the right folder before I update the page. Will do today.

**Pull request merged**
